stakeoptions/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from stake.views import main_view, signup_view, login_view, logout_view, dashboard_view, buy_stake_view, confirm_buy_stake_view, shares_update, deactivate_share_trade, activate_share_trade, staff_shares_update, raise_dispute_view, dispute_view
from stake.views import confirm_paid_view, approve_paid_view,cancel_trade_view, shares_view, transactions_view, nofifications_view, support_view, users_view, ChartData, deactivate_staff_shares, activate_staff_shares, deactivate_user_shares, activate_user_shares

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', main_view, name='main-view'),
    path('signup/', signup_view, name='signup-view'),
    path('login/', login_view, name='login-view'),
    path('logout/', logout_view, name='logout-view'),



    path('dashboard/', dashboard_view, name='dashboard-view'),
    path('buy_stake/', buy_stake_view, name='buy-stake-view'),
    path('shares/', shares_view, name='shares-view'),
    path('transactions/', transactions_view, name='transactions-view'),
    path('transactions/<str:slug>/', confirm_buy_stake_view, name='confirm-buy-stake-view'),
    path('transactions/<str:slug>/pay/', confirm_paid_view, name='confirm-paid-view'),
    path('transactions/<str:slug>/approve/', approve_paid_view, name='approve-paid-view'),
    path('transactions/<str:slug>/cancel/', cancel_trade_view, name='cancel-paid-view'),
    path('transactions/dispute/<str:slug>/', raise_dispute_view, name='raise-dispute-view'),
    path('transactions/<str:dis_pute_id>/dispute/', dispute_view, name='dispute-view'),



    path('shares-update/', shares_update, name='shares-update-view'),
    path('staff-shares-update/', staff_shares_update, name='staff-shares-update-view'),
    path('shares-update/deactivate/<str:shared>/', deactivate_share_trade, name='deactivate-share-view'),
    path('shares-update/activate/<str:shared>/', activate_share_trade, name='activate-share-view'),
    path('activate-staff/', deactivate_staff_shares, name='deactivate-staff-shares-view'),
    path('deactivate-staff/', activate_staff_shares, name='activate-staff-shares-view'),
    path('activate-user/', deactivate_user_shares, name='deactivate-user-shares-view'),
    path('deactivate-user/', activate_user_shares, name='activate-user-shares-view'),


    path('notifications/', nofifications_view, name='notification-view'),
    path('support/', support_view, name='support-view'),
    path('users/', users_view, name='users-view'),


    path('api/data', ChartData.as_view(), name='api-data'),


    path('reset_password/', auth_views.PasswordResetView.as_view(template_name = "recoverpw-1.html"), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name = "recoverpw_sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = "recoverpw_set.html"), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = "recoverpw_complete.html"), name='password_reset_complete'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stake/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import generate_code


class Profile(models.Model):
    
    user= models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.IntegerField(unique=True, null=True)



class Shares(models.Model):
    
    P_CHOICES = [
            ('4 days(30%)', '4 days(30%)'),
            ('7 days(50%)', '7 days(50%)'),
    ]

    S_CHOICES = [
            ('maturing', 'maturing'),
            ('matured', 'matured'),
            ('completed', 'completed')
    ]
    

    user= models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.IntegerField(null=False)
    interest_period = models.CharField(max_length=30, choices=P_CHOICES)
    status = models.CharField(max_length=30, choices=S_CHOICES)
    expected_payout =models.IntegerField()
    received_payment = models.IntegerField(default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    maturity_date = models.DateTimeField(null=True, blank=True)
    active_trade = models.BooleanField(default=True)
    

    def __str__(self):
        return '%s, %s, %s, %s, %s, %s, %s' %  (self.user, self.amount, self.interest_period, self.status, self.expected_payout, self.received_payment, self.date_created)



class Transaction(models.Model):

    T_CHOICES = [
            ('pending', 'pending'),
            ('cancelled', 'cancelled'),
            ('paid', 'paid'),
            ('approved', 'approved')
    ]
    
    P_CHOICES = [
            ('4 days(30%)', '4 days(30%)'),
            ('7 days(50%)', '7 days(50%)'),
    ]

    
    trans_id = models.CharField(max_length=12, blank=True, unique=True)
    amount = models.IntegerField(null=False)
    status = models.CharField(max_length=30, choices=T_CHOICES, default='pending')
    interest_period = models.CharField(max_length=30, choices=P_CHOICES)
    payer = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    receiver = models.ForeignKey(Shares, on_delete=models.CASCADE, null=True, blank=True)
    screenshot = models.FileField(null=True, blank=True)
    date_created = models.DateField(auto_now_add=True)
    last_updated =models.DateField(auto_now=True)
    slug = models.SlugField(null=True, blank=True)
    dispute_status = models.BooleanField(default=False)

    



    def __str__(self):
        return '%s, %s, %s, %s, %s, %s' % (self.trans_id, self.payer, self.amount, self.interest_period, self.receiver.user, self.receiver)


    def save(self, *args, **kwargs):
        if self.trans_id == "":
            ref_code = generate_code()
            code = ref_code
            self.trans_id = code
            self.slug = code

        super().save(*args, **kwargs)



class Volume(models.Model):

    amount = models.IntegerField(default=0, null=True, blank=True)
    date_created = models.DateField(auto_now_add=True)

    def __str__(self):
        return '%s, %s' % (self.amount, self.date_created)



class AdminNotification(models.Model):

    title = models.CharField(max_length=100)
    description = models.TextField()
    date_created = models.DateField(auto_now_add=True)

    def __str__(self):
        return '%s, %s' % (self.title, self.date_created)


class Dispute(models.Model):

    S_CHOICES = [
            ('pending', 'pending'),
            ('awarded', 'awarded')
    ]

    trans = models.OneToOneField(Transaction, on_delete=models.CASCADE)
    payer_screenshot = models.ImageField(upload_to='uploads/', blank=True, null=True)
    receiver_screenshot = models.ImageField(upload_to='uploads/', blank=True, null=True)
    payer_text = models.CharField(max_length=300, blank=True, null=True)
    receiver_text = models.CharField(max_length=300, blank=True, null=True)
    moderator_text = models.CharField(max_length=300, blank=True, null=True)
    status = models.CharField(max_length=10, choices=S_CHOICES, default='pending')


    def __str__(self):
        return '%s' % (self.trans)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8" />
    <title>Stakesoptions | P2P</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Altcoins and NFT P2P marketplace" name="description" />
    <meta content="Digiland" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static '/assets/images/favicon/favicon.ico' %}" > 

    <!-- DataTables -->
    <link href="{% static '/dashboard/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static '/dashboard/assets/libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
    
    <!-- Bootstrap Css -->
    <link href="{% static '/dashboard/assets/css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="{% static '/dashboard/assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="{% static '/dashboard/assets/css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css" />

    

</head>

<body data-sidebar="dark">

{% block content %}

{% endblock %}


    <!-- JAVASCRIPT -->
    <script src="{% static '/dashboard/assets/libs/jquery/jquery.min.js' %}"></script>
    <script src="{% static '/dashboard/assets/libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static '/dashboard/assets/libs/metismenu/metisMenu.min.js' %}"></script>
    <script src="{% static '/dashboard/assets/libs/simplebar/simplebar.min.js' %}"></script>
    <script src="{% static '/dashboard/assets/libs/node-waves/waves.min.js' %}"></script>
    <script src="{% static '/dashboard/assets/libs/jquery-sparkline/jquery.sparkline.min.js' %}"></script>

    <!-- Chart JS -->
    <script src="{% static '/dashboard/assets/libs/chart.js/Chart.bundle.min.js' %}"></script>
    <script src="{% static '/dashboard/assets/js/pages/chartjs.init.js' %}"></script>

    <script src="{% static '/dashboard/assets/js/pages/dashboard.init.js' %}"></script>

    <!-- Required datatable js -->
    <script src="{% static '/dashboard/assets/libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static '/dashboard/assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <!-- Buttons examples -->
    <script src="{% static '/dashboard/assets/libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static '/dashboard/assets/libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static '/dashboard/assets/libs/jszip/jszip.min.js' %}"></script>
    <script src="{% static '/dashboard/assets/libs/pdfmake/build/pdfmake.min.js' %}"></script>
    <script src="{% static '/dashboard/assets/libs/pdfmake/build/vfs_fonts.js' %}"></script>
    <script src="{% static '/dashboard/assets/libs/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static '/dashboard/assets/libs/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static '/dashboard/assets/libs/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>
    
    <!-- Responsive examples -->
    <script src="{% static '/dashboard/assets/libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static '/dashboard/assets/libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

    <!-- Datatable init js -->
    <script src="{% static '/dashboard/assets/js/pages/datatables.init.js' %}"></script>

    <!-- forms -->
    <script src="{% static '/dashboard/assets/libs/parsleyjs/parsley.min.js' %}"></script>

    <script src="{% static '/dashboard/assets/js/pages/form-validation.init.js' %}"></script>    

    <!-- App js -->
    <script src="{% static '/dashboard/assets/js/app.js' %}"></script>


</body>

</html>

templates/buy.html
{% extends "base2.html" %}
{% load static %}
{% load humanize %}

{% block page %}
    

<div class="main-content">

    <div class="page-content">
        <div class="container-fluid">


            <div class="row">

                <div class="col-xl-12">
                    <div class="card">
                        <div class="card-body">
                        
                            <h1 class="text-primary">Buy Shares</h1>
                            <p>Buy shares from other users via m-pesa.The system will pair you automatically with another user who you will trade with. 
                                Only send payment to the number provided in the instructions incase a dispute arises
                            </p>


                        </div>
                    </div>
                </div>
            </div>



            <div class="row">

                <div class="col-xl-3 col-md-6">
                    <div class="card mini-stat bg-dark">
                        <div class="card-body mini-stat-img">
                            <div class="mini-stat-icon">
                                <i class="mdi mdi-cube-outline float-right"></i>
                            </div>
                            <div class="text-white">
                                <h6 class="text-uppercase mb-4 font-size-16">24H Volume Change</h6>
                                {%if today_data_sum > yesterday_data_sum %}
                                <h4 class=" mt-4 text-success"><i class="mdi mdi-arrow-up-thick"></i>{{percent_change}}%</h4>

                                {%elif yesterday_data_sum > today_data_sum %}
                                <h4 class=" mt-4 text-danger"><i class="mdi mdi-arrow-down-thick"></i>{{percent_change}}%</h4>

                                {%elif percent_change == 'N/A' %}
                                <h4 class=" mt-4 text-danger">{{percent_change}}</h4>

                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card mini-stat bg-dark">
                        <div class="card-body mini-stat-img">
                            <div class="mini-stat-icon">
                                <i class="mdi mdi-buffer float-right"></i>
                            </div>
                            <div class="text-white">
                                <h6 class="text-uppercase mb-4 font-size-16">24H Volume Traded</h6>
                                <h4 class=" mt-4 text-success">Ksh {{today_data_sum|intcomma}}</h4>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card mini-stat bg-dark">
                        <div class="card-body mini-stat-img">
                            <div class="mini-stat-icon">
                                <i class="mdi mdi-tag-text-outline float-right"></i>
                            </div>
                            <div class="text-white">
                                <h6 class="text-uppercase mb-3 font-size-16">7D Volume Traded</h6>
                                <h4 class="mt-4 text-warning">Ksh {{seven_day_data_sum|intcomma}}</h4>
                                <!-- <span class="badge badge-warning"> 0% </span> <span class="ml-2">compared to prev. day</span> -->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card mini-stat bg-dark">
                        <div class="card-body mini-stat-img">
                            <div class="mini-stat-icon">
                                <i class="mdi mdi-briefcase-check float-right"></i>
                            </div>
                            <div class="text-white ">
                                <h6 class="text-uppercase mb-3 font-size-16">Market </br>Capitalization</h6>
                                <h5 class="mt-4 font-size-18 text-primary">Ksh {{market_cap|intcomma}}</h5>
                                <!-- <span class="badge badge-info"> +89% </span> <span class="ml-2">compared to prev. day</span> -->
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="row mt-0 ml-2">Last Updated {{last_updated}} UTC</div>

            <div class="row">

                <div class="col-lg-4 mb-0 ">
                    <div class="card" style="background-color: pink;" >
                        <div class="card-body ">
                            <h1 class="text-primary">Buy</h1>

                            <h5 class="text-info">Available Shares: Ksh {{total_available_shares|intcomma}}</h5>

                            <form class="" action="." method="POST">

                                {% csrf_token %}


                                {% if form.errors %}
                                    {% for field in form %}
                                        {% for error in field.errors %}
                                            <div class="alert alert-danger">
                                                <strong>{{ field.label }} : </strong><span>{{ error|escape }}</strong>
                                            </div>
                                        {% endfor %}
                                    {% endfor %}
                                    {% for error in form.non_field_errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{ error|escape }}</strong>
                                        </div>
                                    {% endfor %}
                                {% endif %}

                                <div class="form-group">
                                    <label for="id_amount" class="text-black">Amount</label>
                                    <div>
                                        {{form.amount}}
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="text-black col-form-label">Select</label>
                                    <div class="">
                                        
                                            {{form.interest_period}}
                                        
                                    </div>
                                </div>

                                <div class="form-group">
                                    
                                    <div class="mt-4">
                                        <label class="mt-2 row text-black"><h5 class="ml-2">Expected Return:</h5><h5 class="ml-2 text-info">Ksh 650</h5></label>
                                    </div>
                                </div>

                                <div class="form-group mb-0">
                                    <div>
                                        <button type="submit" class="btn btn-primary waves-effect waves-light mr-1">
                                            Submit
                                        </button>
                                        <button type="reset" class="btn btn-secondary waves-effect">
                                            Cancel
                                        </button>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>

                <div class="col-lg-8 mb-0">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title mb-4">Daily Volumes Traded</h4>

                            <canvas id="line_1" height="150"></canvas>
                            

                        </div>
                    </div>
                </div>

            </div>

            <div class="row">

                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-body">

                            <h4 class="card-title mb-4">Daily Bought analysis</h4>
                            <p>Total amount of shares bought </p>

                            <canvas id="bar" height="200"></canvas>

                        </div>
                    </div>
                </div>
                <!-- end col -->

                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-body">

                            <h4 class="card-title mb-4">Daily Returns Analysis</h4>
                            <p>Total amount of profits made</p>

                            <canvas id="bar2" height="200"></canvas>

                        </div>
                    </div>
                </div>
                <!-- end col -->

            </div>
            <!-- end row -->
            </div>


            
                           


        </div>
        <!-- end row -->


        </div>
    </div>
</div>

{% endblock %}

templates/login.html
{% extends "base2.html" %}
{% load static %}

{% block content %}

<div class="account-pages my-5 pt-sm-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 col-lg-6 col-xl-5">
                <div class="card overflow-hidden">
                    <div class="card-body pt-0">
                        <h3 class="text-center mt-4">
                            <a href="{% url 'main-view' %}" class="logo logo-admin"><img src="{% static '/assets/images/logo/logo.png' %}"
                                    height="60" alt="logo"></a>
                        </h3>
                        <div class="p-3">
                            <h4 class="text-muted font-size-18 mb-1 text-center">Welcome Back !</h4>
                            <p class="text-muted text-center">Sign in to continue.</p>
                            <form class="form-horizontal mt-4" action="." method="POST">
                                {% csrf_token %}

                                <div class="form-group">
                                    <label for="username">Username / Email</label>
                                    {{ form.query }}
                                </div>
                                <div class="form-group">
                                    <label for="userpassword">Password</label>
                                    {{ form.password }}
                                </div>

                                {% if form.errors %}
                                    {% for field in form %}
                                        {% for error in field.errors %}
                                            <div class="alert alert-danger">
                                                <strong>{{ field.label }} : </strong><span>{{ error|escape }}</strong>
                                            </div>
                                        {% endfor %}
                                    {% endfor %}
                                    {% for error in form.non_field_errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{ error|escape }}</strong>
                                        </div>
                                    {% endfor %}
                                {% endif %}

                                <div class="form-group row mt-4">
                                    <div class="col-6">
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="customControlInline">
                                            <label class="custom-control-label" for="customControlInline">Remember me
                                            </label>
                                        </div>
                                    </div>
                                    <div class="col-6 text-right">
                                        <button class="btn btn-primary w-md waves-effect waves-light" type="submit">Log In</button>
                                    </div>
                                </div>
                                <div class="form-group mb-0 row">
                                    <div class="col-12 mt-4">
                                        <a href="{% url 'reset_password' %}" class="text-muted"><i class="mdi mdi-lock"></i> Forgot your password?</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="mt-5 text-center">
                    <p>Don't have an account ? <a href="{% url 'signup-view' %}" class="text-primary"> Signup Now </a></p>
                    <p>© stakes-options 2021</p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/signup.html
{% extends "base2.html" %}
{% load static %}

{% block content %}
    <div class="account-pages my-5 pt-sm-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-5">
                    <div class="card overflow-hidden">
                        <div class="card-body pt-0">
                            <h3 class="text-center mt-4">
                                <a href="{% url 'main-view' %}" class="logo logo-admin"><img src="{% static '/assets/images/logo/logo.png' %}"
                                        height="60" width="125" alt="logo"></a>
                            </h3>
                            <div class="p-3">
                                <h4 class="text-muted font-size-18 mb-1 text-center">Free Registration</h4>
                                <p class="text-muted text-center">Get your account now.</p>
                                <form class="form-horizontal mt-4" action="." method="POST">
                                    {% csrf_token %}

                                    <div class="form-group">
                                        <label for="username">Username</label>
                                        <input type="text" class="form-control" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" id="id_username" placeholder="Enter username">
                                    </div>

                                    <div class="form-group">
                                        <label for="userfirstname">First Name</label>
                                        <input type="text" class="form-control" name="first_name" maxlength="150" id="id_first_name" placeholder="First Name">
                                    </div>

                                    <div class="form-group">
                                        <label for="userlastname">Last Name</label>
                                        <input type="text" class="form-control" name="last_name" maxlength="150" id="id_last_name" placeholder="Last Name">
                                    </div>

                                    <div class="form-group">
                                        <label for="useremail">Email</label>
                                        <input type="email" class="form-control" name="email" maxlength="254" id="id_email" placeholder="Enter email">
                                    </div>

                                    <div class="form-group">
                                        <label for="userphone">Phone number</label>
                                        <input type="number" class="form-control" name="phone_number" required="" id="id_phone_number" placeholder="Phone Number">
                                    </div>

                                    <div class="form-group">
                                        <label for="userpassword">Password</label>
                                        <input type="password" class="form-control" name="password1" autocomplete="new-password" required="" id="id_password1" placeholder="Enter password">
                                    </div>

                                    <div class="form-group">
                                        <label for="userpassword">Confirm Password</label>
                                        <input type="password" class="form-control" name="password2" autocomplete="new-password" required="" id="id_password2" placeholder="Confirm password">
                                    </div>

                                    <div class="form-group row mt-4">
                                        <div class="col-12 text-right">
                                            <button class="btn btn-primary w-md waves-effect waves-light" type="submit">Register</button>
                                        </div>
                                    </div>

                                    <div class="form-group mb-0 row">
                                        <div class="col-12 mt-4">
                                            <p class="text-muted mb-0 font-size-14">By registering you agree to the digiland <a href="#" class="text-primary">Terms of Use</a></p>
                                        </div>
                                    </div>



                                    {% if form.errors %}
                                        {% for field in form %}
                                            {% for error in field.errors %}
                                                <div class="alert alert-danger">
                                                    <strong>{{ field.label }} : </strong><span>{{ error|escape }}</strong>
                                                </div>
                                            {% endfor %}
                                        {% endfor %}
                                        {% for error in form.non_field_errors %}
                                            <div class="alert alert-danger">
                                                <strong>{{ error|escape }}</strong>
                                            </div>
                                        {% endfor %}
                                    {% endif %}

                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="mt-5 text-center">
                        <p>Already have an account ? <a href="{% url 'login-view' %}" class="text-primary"> Login </a> </p>
                        <p>© Digiland 2021</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}